### ISSUE TITLE
Tracking issue 9.16-9.30

### ISSUE THREAD

**Issue by beyang** [sourcegraph/community#34]
@beyang 
- [ ] Intro notebook

@jdorfman 
- [x] [4.0] Product Hunt
- [x] [4.0] [Update sourcegraph/sourcegraph README](https://github.com/sourcegraph/community/issues/33)
- [x] 10/3, 10-11am Livestream with Jason Laster

Unassigned
- [ ] Blog post CTAs
  * in the middle, point to Discord (drop them into "try out Sourcegraph" channel)
  * at the bottom, point to Cloud
  * Discord welcome message

Future
* Livestreams
  * Sourcegraph codebase tour with an application engineer
